<?php

namespace App\Filament\Resources\GeneratedExports\Tables;

use App\Models\GeneratedExport;
use Filament\Actions\Action;
use Filament\Actions\ViewAction;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class GeneratedExportsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('export_type')->label('Export type')->searchable()->sortable(),
                TextColumn::make('file_name')
                    ->label('File')
                    ->state(fn (GeneratedExport $record): ?string => $record->file_path ? basename($record->file_path) : null)
                    ->searchable(['file_path']),
                TextColumn::make('status')->badge()->sortable(),
                TextColumn::make('generator.name')->label('Generated by')->sortable(),
                TextColumn::make('generated_at')->dateTime()->sortable(),
            ])
            ->filters([
                SelectFilter::make('status')
                    ->options([
                        'generated' => 'Generated',
                        'failed' => 'Failed',
                    ]),
                SelectFilter::make('export_type')
                    ->options([
                        'ckpn_workpaper_sakep_xlsx' => 'CKPN workpaper SAKEP XLSX',
                    ]),
            ])
            ->recordActions([
                ViewAction::make(),
                Action::make('download')
                    ->label('Download')
                    ->icon(Heroicon::OutlinedArrowDownTray)
                    ->visible(fn (GeneratedExport $record): bool => $record->status === GeneratedExport::STATUS_GENERATED
                        && filled($record->file_path)
                        && (auth()->user()?->can('view', $record) ?? false))
                    ->url(fn (GeneratedExport $record): string => route('generated-exports.download', $record))
                    ->openUrlInNewTab(),
            ]);
    }
}
