<?php

namespace App\Filament\Resources\GeneratedExports\Tables;

use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class GeneratedExportsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('export_type')->label('Export type')->searchable()->sortable(),
                TextColumn::make('file_path')->label('File path')->searchable()->sortable(),
                TextColumn::make('status')->badge()->sortable(),
                TextColumn::make('generator.name')->label('Generated by')->sortable(),
                TextColumn::make('generated_at')->dateTime()->sortable(),
            ])
            ->filters([
                SelectFilter::make('status')
                    ->options([
                        'generated' => 'Generated',
                        'failed' => 'Failed',
                    ]),
                SelectFilter::make('export_type')
                    ->options([
                        'ckpn_workpaper_sakep_xlsx' => 'CKPN workpaper SAKEP XLSX',
                    ]),
            ])
            ->recordActions([
                ViewAction::make(),
            ]);
    }
}
