<?php

namespace App\Filament\Resources\GeneratedExports\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class GeneratedExportInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Export details')
                    ->inlineLabel()
                    ->columnSpanFull()
                    ->schema([
                        TextEntry::make('export_type')->label('Export type'),
                        TextEntry::make('status')->badge(),
                        TextEntry::make('file_path')->label('File path')->columnSpanFull(),
                        TextEntry::make('generator.name')->label('Generated by'),
                        TextEntry::make('generated_at')->dateTime(),
                        TextEntry::make('metadata')
                            ->formatStateUsing(fn(array|string|null $state): ?string => is_array($state)
                                ? json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
                                : $state)
                            ->columnSpanFull(),
                    ]),
            ]);
    }
}
